import 'modules/admin-lte/plugins/jQueryUI/jquery-ui.min'
import 'modules/admin-lte/dist/js/adminlte.min'
import 'modules/bootstrap/dist/js/bootstrap.min'
import 'modules/jquery/dist/jquery.min'

import 'modules/font-awesome/css/font-awesome.min.css'
import 'modules/ionicons/dist/css/ionicons.min.css'
import 'modules/bootstrap/dist/css/bootstrap.min.css'
import 'modules/admin-lte/dist/css/AdminLTE.min.css'
import 'modules/admin-lte/dist/css/skins/_all-skins.min.css'
import 'modules/admin-lte/plugins/iCheck/flat/blue.css'
import 'modules/admin-lte/plugins/bootstrap-slider/slider.css'
import 'modules/admin-lte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css'

import './custom.css'